### ISSUE TITLE
About the css and js files mentioned in index.html

### ISSUE THREAD

**Issue by LizzyEw** [zhongjinluo/Sketch2RaBit#2]
Hi, there! Thank you very much for your excellent work. 
I can't find the css and js files mentioned in line 15-39 of the index.html. Could you please tell me where they are? I want to try the system according to your instructions, but get errors when running the server.sh and run.sh.
Thank you for your message!

**Comment by LizzyEw** [comment]
I would appreciate it if you could supplement the js&css files and pre-trained models. Thanks again!

**Comment by zhongjinluo** [comment]
You can use our pre-compiled user interface.

**Comment by LizzyEw** [comment]
Thank you for your early reply, I will look into this further. Best of luck with your future research :)
